language: csharp
solution: src/TeamCityTheatre.sln
mono: none
dotnet: 1.0.4
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
script:
 - ./build.sh --target publish --verbosity diagnostic